/* eslint-disable */
/**
 * Generated utilities for interacting with Convex.
 *
 * THIS CODE IS INTENDED TO BE GENERATED BY CONVEX.
 * 
 * For now, this is a placeholder that allows the app to run without Convex.
 * Run `npx convex dev` to generate the actual client.
 */

// Placeholder API type
export type Api = {
  motels: {
    createOrUpdateUser: Function;
    getUserByClerkId: Function;
    updateUserRole: Function;
    createMotel: Function;
    getMotels: Function;
    getMotelById: Function;
    getMotelsByOwner: Function;
    updateMotel: Function;
    deleteMotel: Function;
    approveMotel: Function;
    rejectMotel: Function;
    toggleMotelStatus: Function;
    incrementViewCount: Function;
    createReview: Function;
    getReviewsByMotel: Function;
    trackContact: Function;
    getOwnerStats: Function;
    getAdminStats: Function;
  };
};

// Placeholder for the API
export const api: Api = {
  motels: {
    createOrUpdateUser: (() => {}) as unknown as Function,
    getUserByClerkId: (() => {}) as unknown as Function,
    updateUserRole: (() => {}) as unknown as Function,
    createMotel: (() => {}) as unknown as Function,
    getMotels: (() => {}) as unknown as Function,
    getMotelById: (() => {}) as unknown as Function,
    getMotelsByOwner: (() => {}) as unknown as Function,
    updateMotel: (() => {}) as unknown as Function,
    deleteMotel: (() => {}) as unknown as Function,
    approveMotel: (() => {}) as unknown as Function,
    rejectMotel: (() => {}) as unknown as Function,
    toggleMotelStatus: (() => {}) as unknown as Function,
    incrementViewCount: (() => {}) as unknown as Function,
    createReview: (() => {}) as unknown as Function,
    getReviewsByMotel: (() => {}) as unknown as Function,
    trackContact: (() => {}) as unknown as Function,
    getOwnerStats: (() => {}) as unknown as Function,
    getAdminStats: (() => {}) as unknown as Function,
  },
};

// Internal API (same as api for now)
export const internal: Api = api;

export default api;
